### Example 1: Change password to "newpassword"
POST http://192.168.4.1/change_password HTTP/1.1
Content-Type: text/plain
Content-Length: 10

newpassword


### Example 2: Change password to "12345678"
POST http://192.168.4.1/change_password HTTP/1.1
Content-Type: text/plain
Content-Length: 8

12345678


### Example 3: Change password to "openwifi" (No password)
POST http://192.168.4.1/change_password HTTP/1.1
Content-Type: text/plain
Content-Length: 8

openwifi
